# Generates and Uploads PDFs to Firebase Storage bucket.

name: Upload PDFs
on:
  push:
    paths:
      - 'generator/**'
      - '.github/workflows/**'

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: [frequency, grade, jlpt, kanjigarden, wanikani]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get npm cache directory path
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache/Restore
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install NPM dependencies
        run: npm install

      - name: Build Remix app
        run: npm run build

      - name: Generate PDF files
        run: npx remix-serve build
        env:
          BUILD_WORKSHEETS: true
          COLLECTION: ${{ matrix.source }}
